#!/bin/bash

VERSION=1.8.0
PACKAGE=rich-cli
TOOL=rich
DIRECTORY=$(dirname $0)

STORAGES=(/ocean /bil /hive /local)

OPTIONS=""
for STORAGE in "${STORAGES[@]}"
do
	if [ -d "$STORAGE" ]; then
		OPTIONS=$OPTIONS" -B $STORAGE"
	fi
done

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
